# Algorithm 2
#Fibonacci Sequence
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence 
# whose values do not exceed four million, find the sum of the even-valued terms


fib1 = 1
fib2 = 2
sum_total = 0

while(sum_total < 4000000):
    if(fib1 % 2 == 0):
        sum_total += fib1
    new_fib = fib1 + fib2
    fib1 = fib2
    fib2 = new_fib
    
print sum_total
